name: Use Central Lint

on:
  push:
    branches: [main]
  pull_request:
  
jobs:
  lint:
    uses: Alayanos/devops-actions-poc/.github/workflows/lint-golangci.yml@main
    with:
      go-version: '1.21.5'
