name: Use Central Lint

on:
  push:
    branches: [main]
  pull_request:
  
jobs:
  lint:
    uses: Alayanos/devops-actions-poc/.github/workflows/lint-golangci.yml@main
    with:
      go-version: 'go1.24.2.linux-amd64.tar.gz'
