name: Use Central Go Test

on:
  push:
    branches: [main]
  pull_request:
  
jobs:
  test:
    uses: Alayanos/devops-actions-poc/.github/workflows/go-test.yml@main
    with:
      go-version: '1.21'
